/**
 * Copies the tool catalogue and every choice list from the site's data modules
 * into apps-script/Code.gs, between the GENERATED markers.
 *
 * The Apps Script needs the full rosters to build one column per answer, up
 * front, in the curated order. A second hand-maintained copy over there would
 * drift the first time someone edits the site and forgets — and the symptom
 * would be a silently missing column, not an error.
 *
 *   npm run sync:tools              rewrite the block
 *   npm run sync:tools -- --check   fail if it is out of date (no writes)
 *
 * Node runs the .ts imports directly via type stripping — no build step.
 */
import fs from "node:fs"

const CODE_PATH = new URL("../apps-script/Code.gs", import.meta.url)
const START = "/* === GENERATED by `npm run sync:tools` — do not edit by hand === */"
const END = "/* === END GENERATED === */"

const { TOOL_GROUPS, TOOL_BY_ID } = await import("../src/data/tools.ts")
const profile = await import("../src/data/profile.ts")
const en = JSON.parse(fs.readFileSync(new URL("../src/i18n/locales/en.json", import.meta.url)))

/** Walks "a.b.c" through the locale object. Sheet headers are English by design. */
const label = (key) => key.split(".").reduce((node, part) => node?.[part], en)

const js = (value) => JSON.stringify(value)
const row = (id, text) => `  { id: ${js(id)}, label: ${js(text)} }`

const choiceList = (choices) => choices.map((c) => row(c.id, label(c.labelKey))).join(",\n")

/**
 * Distinct tools — 204, not the 300 checkboxes. The sheet gets one column per
 * tool holding the areas it was picked in, so a tool that lives in eight
 * categories still only costs one column.
 */
const toolRows = Object.entries(TOOL_BY_ID)
  .map(([id, tool]) => row(id, tool.name))
  .join(",\n")

const groupRows = TOOL_GROUPS.map((g) => row(g.id, label(g.labelKey))).join(",\n")

const checkboxes = TOOL_GROUPS.reduce((n, g) => n + g.tools.length, 0)

const block = `${START}
// Source: src/data/tools.ts, src/data/profile.ts, src/i18n/locales/en.json
// ${Object.keys(TOOL_BY_ID).length} distinct tools (${checkboxes} checkboxes across ${TOOL_GROUPS.length} areas).

var TOOL_ROSTER = [
${toolRows}
]

var AREA_ROSTER = [
${groupRows}
]

var EXPERTISE_ROSTER = [
${choiceList(profile.PRIMARY_EXPERTISE)}
]

var PRACTICE_ROSTER = [
${choiceList(profile.PRACTICE_AREAS)}
]

var AI_WORKFLOW_ROSTER = [
${choiceList(profile.AI_WORKFLOW)}
]

var AI_RELATIONSHIP_ROSTER = [
${choiceList(profile.AI_RELATIONSHIP)}
]

var PROJECT_TYPE_ROSTER = [
${choiceList(profile.PROJECT_TYPES)}
]

var STAGE_ROSTER = [
${choiceList(profile.PIPELINE_STAGES)}
]
${END}`

const source = fs.readFileSync(CODE_PATH, "utf8")
const startAt = source.indexOf(START)
const endAt = source.indexOf(END)

if (startAt === -1 || endAt === -1) {
  console.error(`Markers not found in Code.gs. Expected:\n${START}\n${END}`)
  process.exit(1)
}

const next = source.slice(0, startAt) + block + source.slice(endAt + END.length)

if (process.argv.includes("--check")) {
  if (next !== source) {
    console.error("Code.gs is out of date with src/data — run: npm run sync:tools")
    process.exit(1)
  }
  console.log("Code.gs rosters are in sync")
  process.exit(0)
}

fs.writeFileSync(CODE_PATH, next)
console.log(
  `synced ${Object.keys(TOOL_BY_ID).length} tools, ${TOOL_GROUPS.length} areas, ` +
    `${profile.PRACTICE_AREAS.length} practice areas, ${profile.PIPELINE_STAGES.length} stages, ` +
    `${profile.PROJECT_TYPES.length} project types into Code.gs`
)
