/**
 * Copies the tool / role / published-work rosters from the site's data modules
 * into apps-script/Code.gs, between the GENERATED markers.
 *
 * The Apps Script needs the full roster to build one column per tool up front,
 * in the curated order. Keeping a second hand-maintained copy over there would
 * drift the first time someone adds a tool to the site and forgets — and the
 * symptom would be a silently missing column, not an error.
 *
 * So: one source of truth (src/data), one generated block, and a check that
 * fails loudly if they ever diverge.
 *
 *   npm run sync:tools          rewrite the block
 *   npm run sync:tools -- --check   fail if it is out of date (no writes)
 *
 * Node runs the .ts imports directly via type stripping — no build step.
 */
import fs from "node:fs"

const CODE_PATH = new URL("../apps-script/Code.gs", import.meta.url)
const START = "/* === GENERATED by `npm run sync:tools` — do not edit by hand === */"
const END = "/* === END GENERATED === */"

const { TOOL_GROUPS } = await import("../src/data/tools.ts")
const { ROLES, PUBLISHED_WORK } = await import("../src/data/profile.ts")
const en = JSON.parse(fs.readFileSync(new URL("../src/i18n/locales/en.json", import.meta.url)))

/** Walks "a.b.c" through the locale object. Headers are English by design. */
const label = (key) => key.split(".").reduce((node, part) => node?.[part], en)

const js = (value) => JSON.stringify(value)

const toolRows = TOOL_GROUPS.flatMap((group) =>
  group.tools.map(
    (tool) =>
      `  { id: ${js(tool.id)}, name: ${js(tool.name)}, group: ${js(group.id)}, ai: ${tool.ai} }`
  )
).join(",\n")

const groupRows = TOOL_GROUPS.map(
  (group) => `  { id: ${js(group.id)}, label: ${js(label(group.labelKey))} }`
).join(",\n")

const chipRows = (chips) =>
  chips.map((chip) => `  { id: ${js(chip.id)}, label: ${js(label(chip.labelKey))} }`).join(",\n")

const block = `${START}
// Source: src/data/tools.ts, src/data/profile.ts, src/i18n/locales/en.json
// ${TOOL_GROUPS.reduce((n, g) => n + g.tools.length, 0)} tools across ${TOOL_GROUPS.length} pipeline stages.

var TOOL_ROSTER = [
${toolRows}
]

var STAGE_ROSTER = [
${groupRows}
]

var ROLE_ROSTER = [
${chipRows(ROLES)}
]

var PUBLISHED_ROSTER = [
${chipRows(PUBLISHED_WORK)}
]
${END}`

const source = fs.readFileSync(CODE_PATH, "utf8")
const startAt = source.indexOf(START)
const endAt = source.indexOf(END)

if (startAt === -1 || endAt === -1) {
  console.error(`Markers not found in Code.gs. Expected:\n${START}\n${END}`)
  process.exit(1)
}

const next = source.slice(0, startAt) + block + source.slice(endAt + END.length)

if (process.argv.includes("--check")) {
  if (next !== source) {
    console.error("Code.gs is out of date with src/data — run: npm run sync:tools")
    process.exit(1)
  }
  console.log("Code.gs roster is in sync")
  process.exit(0)
}

fs.writeFileSync(CODE_PATH, next)
console.log(
  `synced ${TOOL_ROSTER_COUNT()} tools, ${ROLES.length} roles, ${PUBLISHED_WORK.length} published-work types into Code.gs`
)

function TOOL_ROSTER_COUNT() {
  return TOOL_GROUPS.reduce((n, g) => n + g.tools.length, 0)
}
